
<!DOCTYPE html>
<html><body>
<h1>Monet</h1>
<p>Click on the color palette to see the original artwork or source!</p>
<table style="width:100%">
<tr><th style="text-align: center; vertical-align: middle;">Title</th><th style="text-align: center; vertical-align: middle;">ID</th><th style="text-align: center; vertical-align: middle;">Palette</th><th style="text-align: center; vertical-align: middle;">Hex Palette</th></tr><tr><td style="text-align: center; vertical-align: middle;"><a href=https://www.nga.gov/collection/art-object-page.52186.html style="font-size:14px">"Argenteuil"</a></td> <td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">9C28832CD6A3EE47CFF0</p></td> <td style="text-align: center; vertical-align: middle;"><a href=https://www.nga.gov/collection/art-object-page.52186.html style="font-size:14px"><img style="border-radius: 14px;" src="../media/swatches/9C28832CD6A3EE47CFF0.png" height="25"></a></td> <td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">#403A25, #7F7557, #9B926F, #BCC3B5, #625E34</p></td></tr><tr><td style="text-align: center; vertical-align: middle;"><a href=https://www.nga.gov/collection/art-object-page.46652.html style="font-size:14px">"Banks of the Seine Vétheuil"</a></td> <td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">517746D4B3562CC089F7</p></td> <td style="text-align: center; vertical-align: middle;"><a href=https://www.nga.gov/collection/art-object-page.46652.html style="font-size:14px"><img style="border-radius: 14px;" src="../media/swatches/517746D4B3562CC089F7.png" height="25"></a></td> <td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">#4D6A46, #939F77, #88A09D, #A0B0A4, #6E855C</p></td></tr><tr><td style="text-align: center; vertical-align: middle;"><a href=https://www.nga.gov/collection/art-object-page.61379.html style="font-size:14px">"Woman with a Parasol - Madame Monet and Her Son"</a></td> <td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">CE12EAF4B42CD5A293F5</p></td> <td style="text-align: center; vertical-align: middle;"><a href=https://www.nga.gov/collection/art-object-page.61379.html style="font-size:14px"><img style="border-radius: 14px;" src="../media/swatches/CE12EAF4B42CD5A293F5.png" height="25"></a></td> <td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">#3F5841, #737E58, #7D95A3, #B0BFC9</p></td></tr>
</table>
</body></html>
