
<!DOCTYPE html>
<html><body>
<h1>VanGogh</h1>
<p>Click on the color palette to see the original artwork or source!</p>
<table style="width:100%">
<tr><th style="text-align: center; vertical-align: middle;">ID</th><th style="text-align: center; vertical-align: middle;">Palette</th><th style="text-align: center; vertical-align: middle;">Hex Palette</th></tr><tr><td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">EC19AA8DF7FC34FBA246</p></td> <td style="text-align: center; vertical-align: middle;"><a href=https://www.wikiart.org/en/vincent-van-gogh/bulb-fields-1883 style="font-size:14px"><img style="border-radius: 14px;" src="../media/swatches/EC19AA8DF7FC34FBA246.png" height="25"></a></td> <td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">#1E120D, #6A5633, #C0B88A, #A89D68</p></td></tr><tr><td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">398594C27830CDE127E8</p></td> <td style="text-align: center; vertical-align: middle;"><a href=https://www.wikiart.org/en/vincent-van-gogh/entrance-to-the-moulin-de-la-galette-1887 style="font-size:14px"><img style="border-radius: 14px;" src="../media/swatches/398594C27830CDE127E8.png" height="25"></a></td> <td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">#1E120D, #594B2D, #C0B88A, #A89D68, #886940</p></td></tr><tr><td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">0E635CAFABEA9D65D240</p></td> <td style="text-align: center; vertical-align: middle;"><a href=https://www.nga.gov/collection/art-object-page.106382.html style="font-size:14px"><img style="border-radius: 14px;" src="../media/swatches/0E635CAFABEA9D65D240.png" height="25"></a></td> <td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">#1B566C, #5A8B88, #B8BB7F, #937C24</p></td></tr><tr><td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">9B381C78A14EF84DA14C</p></td> <td style="text-align: center; vertical-align: middle;"><a href=https://www.wikiart.org/en/vincent-van-gogh/the-starry-night-1889 style="font-size:14px"><img style="border-radius: 14px;" src="../media/swatches/9B381C78A14EF84DA14C.png" height="25"></a></td> <td style="text-align: center; vertical-align: middle;"><p style="font-size:14px">#1A1D1C, #2B3853, #637C94, #737E63, #A2AA91, #3E5682</p></td></tr>
</table>
</body></html>
